version: '3.9'
services:
  postgres:
    image: 'postgres:13-alpine'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bdaybot
      POSTGRES_PASSWORD: bdaybot
      POSTGRES_USER: bdaybot
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - './bdaybot:/bdaybot/bdaybot:ro'
    depends_on:
      - postgres
